#ifndef _Q4SAGENTSTATE_H_
#define _Q4SAGENTSTATE_H_

enum Q4SAgentState
{   
    Q4SAGENTSTATE_INVALID,
    Q4SAGENTSTATE_INIT,
    Q4SAGENTSTATE_LISTEN,
	Q4SAGENTSTATE_DONE
};

#endif // _Q4SAGENTSTATE_H_